Okta CLI with Fig
oktadev/okta-blog pull request #1046
Opened 2022-01-20 21:19 UTC by alisaduncan

This blog post has the following features:

- [ ] A GitHub Repository with a polished README
- [ ] A GitHub Repository under the github.com/oktadev account
- [x] A title that's approved by Dev Advocacy
- [x] A URL that's approved by Dev Advocacy
- [x] The content has been run through Grammarly (https://www.grammarly.com/)
- [x] Rendered locally and confirmed that no Markdown typos exist

2022-01-20 21:29 UTC, bdemers commented on _source/_posts/2022-01-24-okta-cli-completion.md
> +Getting more detailed help information is easier too! The autocompletion context menu helps you navigate to the help output for a command. And yup, you can get help about `help` command. Pretty meta,
❤️

2022-01-21 17:17 UTC, havi commented on _source/_posts/2022-01-24-okta-cli-completion.md
> +- "Looking to power up your commandline? 💪 Use Okta CLI with @fig for ultimate productivity."
```suggestion
- "Looking to power up your command line? 💪  Use Okta CLI with @fig for ultimate productivity."
```
added space

2022-01-21 18:45 UTC, havi commented on _source/_posts/2022-01-24-okta-cli-completion.md
> +Fig add autocompletion to supported terminals, which makes using CLIs so much easier. Using Git? You'll see a small window pop up with different commands and options.
```suggestion
Fig adds autocompletion to supported terminals, which makes using CLIs so much easier. Using Git? You'll see a small window pop up with different commands and options. 
```
typo

2022-01-21 18:47 UTC, havi commented on _source/_posts/2022-01-24-okta-cli-completion.md
> +CLIs are great. I love the speed and productivity increases I get when using a CLI, but memorizing commands, when commands need arguments, options, flags, and so on, can be daunting. Luckily, there a
```suggestion
CLIs are great. I love the speed and productivity increases I get when using a CLI, but memorizing commands – especially when commands need arguments, options, flags, and so on – can be daunting. Luckily, there are tools available for CLI fans out there, and one tool I've been enjoying is [Fig](https://fig.io/).
```
punctuation tweak to ease readability

2022-01-21 18:57 UTC, havi commented on _source/_posts/2022-01-24-okta-cli-completion.md
> +We're pleased to announce that [Okta CLI](https://cli.okta.com/) autocompletion are available in Fig!  When you use a supported terminal, you'll see hints to help you navigate through the commands an
```suggestion
We're pleased to announce that [Okta CLI](https://cli.okta.com/) autocompletion is available in Fig!  When you use a supported terminal, you'll see hints to help you navigate through the commands and flags, so managing your Okta applications has never been easier.
```
grammar tweaks

2022-01-21 18:58 UTC, havi commented on _source/_posts/2022-01-24-okta-cli-completion.md
> +The autocompletion context menu lists all the commands available and shows you which command requires an argument. The `okta start` command allows you to pass in a name, and you can see the optional
```suggestion
The autocomplete context menu lists all the commands available and shows you which command requires an argument. The `okta start` command allows you to pass in a name, and you can see the optional argument at a glance.
```
using autocomplete to modify the noun "menu"

2022-01-21 19:00 UTC, havi commented on _source/_posts/2022-01-24-okta-cli-completion.md
> +You may need to create Okta apps and get app configurations. When you need to create an Okta app, the Okta CLI is very helpful as it steps you through the process. However, if you are an Okta power u
```suggestion
You may need to create Okta apps and get app configurations. When you need to create an Okta app, the Okta CLI helps you step through the process. However, if you are an Okta power user, you may be fine creating the Okta app in one shot by passing in the app settings. In this case, the Okta CLI autocomplete is pretty handy as it shows you all the options you can pass in!
```
tweaks for terseness & clarity

2022-01-21 19:02 UTC, havi commented on _source/_posts/2022-01-24-okta-cli-completion.md
> +Getting more detailed help information is easier too! The autocompletion context menu helps you navigate to the help output for a command. And yup, you can get help about the `help` command. Pretty m
```suggestion
Getting more detailed help information is easier too! The autocomplete context menu helps you navigate to the help output for a command. And yup, you can get help about the `help` command. Pretty meta, right?
```

2022-01-21 19:09 UTC, havi commented on _source/_posts/2022-01-24-okta-cli-completion.md
> +I hope the autocompletion helps you! I'd love to hear how you use Okta CLI and what tools you use to power up your terminal commands. We welcome issues and PRs in the [okta-cli GitHub repo](https://g
```suggestion
I hope this autocomplete feature helps you! I'd love to hear how you use Okta CLI and what tools you use to power up your terminal commands. We welcome issues and PRs in the [okta-cli GitHub repo](https://github.com/okta/okta-cli) too.
```

2022-01-21 19:12 UTC, havi requested changes
small edits, sweet post.

2022-01-25 14:19 UTC, havi approved these changes
let's ship it!

2022-01-25 14:34 UTC, merged