[New post] Java REST API with Helidon
oktadev/okta-blog pull request #1171
Opened 2022-05-12 23:01 UTC by mraible

This blog post has the following features:

- [ ] A GitHub Repository with a polished README
- [ ] A GitHub Repository under the github.com/oktadev account
- [ ] A title that's approved by Dev Advocacy
- [ ] A URL that's approved by Dev Advocacy
- [ ] The content has been run through Grammarly (https://www.grammarly.com/)
- [ ] Rendered locally and confirmed that no Markdown typos exist

2022-05-24 15:32 UTC, havi commented on _source/_posts/2022-06-01-java-rest-api-helidon.adoc
> +== Generate an OAuth 2.0 Access Token
```suggestion
== Generate an OAuth 2.0 access token
```

2022-05-24 15:33 UTC, havi commented on _source/_posts/2022-06-01-java-rest-api-helidon.adoc
> +. Navigate to the https://oidcdebugger.com/[OpenID Connect Debugger website].
```suggestion
. Navigate to the https://oidcdebugger.com/[OpenID Connect debugger website].
```

2022-05-24 15:34 UTC, havi commented on _source/_posts/2022-06-01-java-rest-api-helidon.adoc
> +=== Run and Test Your Helidon REST API with HTTPie
```suggestion
=== Run and test your Helidon REST API with HTTPie
```

2022-05-24 15:34 UTC, havi commented on _source/_posts/2022-06-01-java-rest-api-helidon.adoc
> +== Startup Time Comparison
```suggestion
== Startup time comparison
```

2022-05-24 15:36 UTC, havi commented on _source/_posts/2022-06-01-java-rest-api-helidon.adoc
> +. Run each image three times before recording the numbers, then each command five times
```suggestion
. Run each image three times before recording the numbers, then each command five times.
```

There's a "1." with no "2." to follow.

2022-05-24 15:36 UTC, havi commented on _source/_posts/2022-06-01-java-rest-api-helidon.adoc
> +== Memory Usage Comparison
```suggestion
== Memory usage comparison
```

2022-05-24 15:43 UTC, havi requested changes
Minor nits re: section headings

2022-05-24 20:33 UTC, mraible commented on _source/_posts/2022-06-02-java-rest-api-helidon.adoc
> +title: "Create a Java REST API with Helidon"
"Fire up a Java REST API with Helidon" might be good too. What do you think @havi?

2022-06-02 02:48 UTC, mraible commented on _source/_posts/2022-06-02-java-rest-api-helidon.adoc
> +    @Produces(TEXT_PLAIN)
```suggestion
    @GET
    @Produces(TEXT_PLAIN)
```

2022-06-02 11:57 UTC, havi commented on _source/_posts/2022-06-02-java-rest-api-helidon.adoc
> +TIP: You can also install the https://helidon.io/docs/v2/#/about/05_cli[Helidon's CLI] and run `helidon init`.
```suggestion
TIP: You can also install https://helidon.io/docs/v2/#/about/05_cli[Helidon's CLI] and run `helidon init`.
```
typo

2022-06-02 11:58 UTC, havi commented on _source/_posts/2022-06-02-java-rest-api-helidon.adoc
> +My MacBook Pro (16-inch, 2021) with Apple M1 Max builds _much_ faster, apps startup 2x faster, but they use more memory.
```suggestion
My MacBook Pro (16-inch, 2021) with Apple M1 Max builds _much_ faster, apps start up 2x faster, but they use more memory.
```
typo

2022-06-02 11:59 UTC, havi requested changes
a couple of small typos.

2022-06-02 13:00 UTC, merged