React Firebase post
oktadev/okta-blog pull request #1194
Opened 2022-06-17 20:47 UTC by alisaduncan

This blog post has the following features:

- [x] A GitHub Repository with a polished README
- [x] A GitHub Repository under the github.com/oktadev account
- [x] A title that's approved by Dev Advocacy
- [x] A URL that's approved by Dev Advocacy
- [x] The content has been run through Grammarly (https://www.grammarly.com/)
- [x] Rendered locally and confirmed that no Markdown typos exist

2022-06-21 14:31 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +Firebase is an exciting Cloud platform from Google available to businesses today.  Firebase connects everything from simple static websites to IoT devices to AI and Machine learning platforms. The pl
```suggestion
Firebase is an exciting cloud platform from Google available to businesses today.  Firebase connects everything from simple static websites to IoT devices to AI and machine learning platforms. The platform provides various services to facilitate these connections, like storage and authentication.
```
clarity 
no capitalization of 'common' nouns

2022-06-21 14:33 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +In this tutorial, you will learn about two core Firebase products; Functions and Hosting. Hosting is for deploying static web applications. Functions are the Firebase serverless platform.  You will c
```suggestion
In this tutorial, you will learn about two core Firebase products: Functions and Hosting. Hosting is for deploying static web applications. Functions are the Firebase serverless platform.  You will create a static application using React that authenticates users via Okta's React library. After obtaining an access token from Okta's authorization server, you will use a Firebase Function to exchange the Okta token for a Firebase token and sign in the user using Firebase's authentication structure. You will obtain additional user information by calling the `userInfo` endpoint on your Okta authorization server and including that data in your Firebase token. Finally, you will create another function endpoint to handle a simple HTTP request that requires an authenticated user.
```

2022-06-21 14:36 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +> [Okta](https://developer.okta.com/) has Authentication and User Management APIs that reduce development time with instant-on, scalable user infrastructure. Okta's intuitive API and expert support m
```suggestion
> [Okta](https://developer.okta.com/) offers Authentication and User Management APIs that reduce development time with instant-on, scalable user infrastructure. Okta's intuitive API and expert support make it easy for developers to authenticate, manage, and secure users and roles in any application.
```
serial comma.

2022-06-21 14:36 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +If you wish, you can follow with the [GitHub repository found here](https://github.com/oktadev/okta-react-firebase-serverless-example).
```suggestion
If you wish, you can follow along with the [GitHub repository found here](https://github.com/oktadev/okta-react-firebase-serverless-example).
```

2022-06-21 14:44 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +Next, open the [Firebase console](https://console.firebase.google.com/u/0/) and click **Add Project**. Give your project a name, preferably `okta-firebase`. You can turn off the analytics for now and
```suggestion
Next, open the [Firebase console](https://console.firebase.google.com/u/0/) and click **Add Project**. Give your project a name, preferably `okta-firebase`. For now, you can turn off the analytics and create the project. Once that's completed, you'll be able to access the project dashboard.  
```
variation

2022-06-21 15:15 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +Click the settings wheel next to *Project Overview* and click **Project settings**. At the bottom of the overview page, there's a prompt to **Select a platform to get started** and select web app (it
```suggestion
Click the settings wheel next to *Project Overview* and click **Project settings**. At the bottom of the overview page, there's a prompt to **Select a platform to get started** and select web app (it will look like *</>*). Give your app the nickname `okta-firebase-demo` and select **Also set up Firebase Hosting for this app**. Click **Register app**, and in a moment you will see some JavaScript code for setting up your Firebase app.
```
clarity

2022-06-21 15:18 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +Finally, click the **Build**>**Authentication** in the side nav and click **Get Started**. Pressing the **Get Started** button generates a **Web API Key** that you will need to use the auth features.
```suggestion
Finally, click the **Build**>**Authentication** in the side nav and click **Get Started**. Pressing the **Get Started** button generates a **Web API Key** that is required for using the auth features. 
```
clarity

2022-06-21 15:21 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +There is currently a known error in React 18 with the Okta React library where multiple rerenders can lead to an error message in the `oktaAuth` object. While fixing the error is ongoing, you can wor
```suggestion
There is currently a known error in React 18 with the Okta React library where multiple rerenders can lead to an error message in the `oktaAuth` object. Work on fixing this error is ongoing. In the meantime, you can work around it by taking React out of `strict` mode. Replace the code in your `index.js` file with the following code.
```
clarifying

2022-06-21 15:25 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
```suggestion
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
```

this feels like a weird place for a bit.ly link. Pls disregard if you think I'm overreacting... Here's the actual link: https://create-react-app.dev/docs/measuring-performance/

2022-06-21 15:26 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +You are replacing the default code with a `Router` and an `AppWithRouterAccess` that you will write next. Add a new file called `AppWithRouterAccess.jsx` and the following code.
```suggestion
You are replacing the default code with a `Router` and an `AppWithRouterAccess` that you will write next. Open a new file called `AppWithRouterAccess.jsx` and add the following code.
```
clarity

2022-06-21 15:30 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +The `getGrades` function ensures the user is authenticated using the build-in authentication function in Firebase. Firebase also integrates with authentication tokens from providers such as Okta. To
```suggestion
The `getGrades` function ensures the user is authenticated using the build-in authentication function in Firebase. Firebase also integrates with authentication tokens from providers such as Okta. To utilize this functionality, you will mint a Firebase authentication token using an Okta authentication token. Okta returns an `accessToken` to the client when the user logs in. The client then passes the `accessToken` to a Firebase function called `exchangeOktaTokenForFirebaseToken`. In this function, you verify the token and return a Firebase token to log the user in. Then subsequent calls to the functions will treat that user as logged in to Firebase.
```
no need to uppercase

2022-06-21 15:32 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +At this point, you can use the `npm run start` command to run your app locally. You'll see a few console errors from Firebase, and you'll see **Login** buttons. At this stage, you'll be able to authe
```suggestion
At this point, you can use the `npm run start` command to run your app locally. You'll see a few console errors from Firebase, and you'll see **Login** buttons. Notice that you're able to authenticate with Okta now, but the login process doesn't call Firebase yet, so your login is incomplete.  
```
sentence variation

2022-06-21 15:33 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +After a moment, you'll see prompts to set up Functions. Select the following options
```suggestion
After a moment, you'll see prompts to set up Firebase Functions. Select the following options:
```
punctuation & capitalization

2022-06-21 15:34 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> + 2. EsLint - **No** (you should use this in production level applications)
```suggestion
 2. EsLint - **No** (You should use this in production-ready applications.)
```

2022-06-21 15:38 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +You should notice that a new folder called `functions` has been added to your directory. There, you will see some Firebase config stuff and a file called `index.js`. You're going to add the code for
```suggestion
You should notice that a new folder called `functions` has been added to your directory. There, you will see some Firebase config stuff and a file called `index.js`. You're going to add the code for two functions.  
```

2022-06-21 15:41 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +First, `exchangeOktaTokenForFirebaseToken` will provide a custom token from Firebase to use in your application. Firebase allows you complete control over your authentication via the `signInWithCusto
```suggestion
First, `exchangeOktaTokenForFirebaseToken` will provide a custom token from Firebase to use in your application. Firebase allows you complete control over your authentication via the `signInWithCustomToken` method you used on the client. You need to create a custom token using your service account. You downloaded your service account definition as a JSON file earlier. Now you can call `createCustomToken` from your `auth` object against your service account. This function requires a `uid` and optionally accepts other claims you may wish to add.  Be mindful that [Firebase reserves token names](https://firebase.google.com/docs/auth/admin/create-custom-tokens#reserved_custom_token_names).  
```

2022-06-21 15:44 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +There are two different ways to set up functions in Firebase, `onCall` and `onRequest`. `onRequest` gives you a more raw form of handling the incoming call. You'd need to set up your CORS code, your
```suggestion
There are two different ways to set up functions in Firebase, `onCall` and `onRequest`. `onRequest` gives you a more raw form of handling the incoming call. You'd need to set up your CORS code, your authentication, and all the good stuff that the `onCall` wrapper takes care of for you. For example, `context.auth` is provided because you used the `onCall`, whereas through `onRequest` you would need to obtain this information manually.  
```

2022-06-21 15:48 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +Open [Okta Developer Portal](https://developer.okta.com/) and **Sign in to Okta**. Then press **Admin** to launch the Admin console.
```suggestion
Open [Okta Developer Portal](https://developer.okta.com/) and **Sign in to Okta**. Then press **Admin** to launch the admin console. 
```

2022-06-21 15:51 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +After completing this step, your CLI will provide you with a URL to your application. You should see your application running on Firebase if you click that. But, Okta won't work at this point. You ne
```suggestion
After completing this step, your CLI will provide a URL to your application. You should see your application running on Firebase if you click that. But, Okta won't work at this point. You need to go back to your Okta admin portal, under your application, and add `{yourFirebaseDomain}/login/callback` to your *Sign-in redirect URIs*, `{yourFirebaseDomain}` to your *Sign-out redirect URIs* to the **General Settings** tab of your Okta application, and add {yourFirebaseDomain} as a **Trusted Origin**  
```
commas in a series

2022-06-21 15:52 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +Now return to your application in Firebase and click **Sign In** to ensure Okta is hooked up correctly. Once you are signed in, you should be able to select a semester and click **Get Grades** to see
```suggestion
Now return to your application in Firebase and click **Sign In** to ensure Okta is hooked up correctly. Once you are signed in, you should be able to select a semester and click **Get Grades** to see your report card generated.
```

2022-06-21 15:52 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +## Review your React app with authenticated Firebase Functions
```suggestion
## Review your React app with authenticated Firebase functions
```

2022-06-21 15:54 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +In this article, you learned how to create and deploy a web application to Google Firebase. You also learned how to build Firebase functions as a backend for your web application. Finally, you learne
```suggestion
In this article, you learned how to create and deploy a web application to Google Firebase. You also learned how to build Firebase functions as a backend for your web application. Finally, you learned how to secure your SPA using Okta and exchange your Okta access token for a Firebase token that it will know how to use in its pipeline. Here are some related articles that might also be of interest: 
```
missing transition

2022-06-21 15:55 UTC, havi requested changes
Small tweaks and changes. Let's use "Firebase functions" without capitalization of "functions" throughout

2022-06-21 18:54 UTC, alisaduncan commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
I agree, but this is what the create-react-app scaffolds out, so this code snippet is exactly as created by the tooling. I will leave it as is so that it's clear to the reader what code bits are changing.

2022-06-21 18:58 UTC, alisaduncan commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +The `getGrades` function ensures the user is authenticated using the build-in authentication function in Firebase. Firebase also integrates with authentication tokens from providers such as Okta. To
The 'Function' here is referring to the Firebase Function. Thoughts on whether it should be changed to "Firebase Function" (or if left lower case, then it should be functions because this Firebase Function has more than one method defined in it)?

2022-06-21 20:00 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +In this tutorial, you will learn about two core Firebase products: Functions and Hosting. Hosting is for deploying static web applications. Functions are the Firebase serverless platform.  You will c
```suggestion
In this tutorial, you will learn about two core Firebase products: Cloud Functions for Firebase and Firebase Hosting. Hosting is for deploying static web applications. Functions are the Firebase serverless platform.  You will create a static application using React that authenticates users via Okta's React library. After obtaining an access token from Okta's authorization server, you will use a Firebase function to exchange the Okta token for a Firebase token and sign in the user using Firebase's authentication structure. You will obtain additional user information by calling the `userInfo` endpoint on your Okta authorization server and including that data in your Firebase token. Finally, you will create another function endpoint to handle a simple HTTP request that requires an authenticated user.
```

2022-06-22 12:56 UTC, alisaduncan commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +In this tutorial, you will learn about two core Firebase products: Functions and Hosting. Hosting is for deploying static web applications. Functions are the Firebase serverless platform.  You will c
Super, thank you!

2022-06-27 14:36 UTC, havi commented on _source/_posts/2022-06-17-react-firebase-serverless.md
> +// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
Got it, will leave as is.

2022-06-27 14:37 UTC, havi approved these changes
Let's ship it !

2022-06-27 14:38 UTC, havi commented on _source/_posts/2022-06-27-react-firebase-serverless.md
> +You can then obtain a token from the Okta authorization server and present it to the Firebase Function to be verified using the `OktaJwtVerifier`. If the Okta token is valid, you will call your Okta
```suggestion
You can then obtain a token from the Okta authorization server and present it to the Firebase function to be verified using the `OktaJwtVerifier`. If the Okta token is valid, you will call your Okta authorization server's `userInfo` endpoint to obtain additional information about your user. You can include this information in your Firebase token as its custom claims. Then you can use the `firebaseApp` object to create your token with those claims. You'll return this token to the client and sign in with it. 
```

2022-06-27 14:43 UTC, havi commented on _source/_posts/2022-06-27-react-firebase-serverless.md
> +[How to Build and Deploy a Serverless React App on Azure](/blog/2022/04/13/react-azure-functions)
```suggestion
- [How to Build and Deploy a Serverless React App on Azure](/blog/2022/04/13/react-azure-functions)
```

2022-06-27 14:43 UTC, havi commented on _source/_posts/2022-06-27-react-firebase-serverless.md
> +[Build a CRUD App with Angular and Firebase](/blog/2019/02/28/build-crud-app-with-angular-and-firebase)
```suggestion
- [Build a CRUD App with Angular and Firebase](/blog/2019/02/28/build-crud-app-with-angular-and-firebase)
```

2022-06-27 14:44 UTC, havi commented on _source/_posts/2022-06-27-react-firebase-serverless.md
> +[Use Firebase with Your ASP.NET MVC App](/blog/2019/04/30/store-data-firebase-aspnet-mvc-csharp)
```suggestion
- [Use Firebase with Your ASP.NET MVC App](/blog/2019/04/30/store-data-firebase-aspnet-mvc-csharp)
```

2022-06-27 14:44 UTC, havi commented on _source/_posts/2022-06-27-react-firebase-serverless.md
> +[Build Reusable React Components](/blog/2020/01/20/build-reusable-react-components)
```suggestion
- [Build Reusable React Components](/blog/2020/01/20/build-reusable-react-components)
```

2022-06-27 14:53 UTC, merged