terraform workshop draft
oktadev/okta-blog pull request #1405
Opened 2023-07-21 01:51 UTC by edunham

todo: 
- [ ] record video
- [ ] add video link (perhaps after publication)
- [ ] fix any typos in render preview
- [ ] add images, at least social image
- [ ] link to tf code all in one spot -- gist? 

This blog post has the following features:

- [ ] A GitHub Repository with a polished README
- [ ] A GitHub Repository under the github.com/oktadev account
- [ ] A title that's approved by Dev Advocacy
- [ ] A URL approved by Dev Advocacy
- [ ] The content has been run through Grammarly (https://www.grammarly.com/)
- [ ] Rendered locally and confirmed that no Markdown typos exist
- [ ] Images are compressed appropriately
- [ ] Social image previews well on Twitter and LinkedIn
- [ ] Tech review request (developer advocate or domain expert)
- [ ] Review request for editorial/grammar/clarity (developer advocate or Colton)

2023-07-21 17:28 UTC, edunham commented on _source/_posts/2023-07-20-terraform-workshop.md
> +type: awareness|conversion
```suggestion
type: awareness|conversion
```
```suggestion
type: awareness
```

2023-07-26 14:59 UTC, edunham commented on _source/_posts/2023-07-20-terraform-workshop.md
> +tags: [terraform,devops,go,automation]
```suggestion
tags: [devops,go,automation]
```

2023-07-27 02:13 UTC, edunham commented
I don't know quite what was wrong with the front matter before, but it's working now.

2023-07-28 16:41 UTC, edunham commented on _source/_posts/2023-07-28-terraform-workshop.md
> +
```suggestion

## Manually create user
```

2023-07-28 16:53 UTC, edunham commented on _source/_posts/2023-07-28-terraform-workshop.md
> +# Setting Up the Okta Terraform Provider
```suggestion
# Set Up the Okta Terraform Provider
```

2023-07-28 16:55 UTC, edunham commented on _source/_posts/2023-07-28-terraform-workshop.md
> +# Set Up the Okta Terraform Provider
```suggestion
## Set Up the Okta Terraform Provider
```

2023-07-28 16:55 UTC, edunham commented on _source/_posts/2023-07-28-terraform-workshop.md
> +# Create the Okta App Integration
```suggestion
## Create the Okta App Integration
```

2023-07-28 16:55 UTC, edunham commented on _source/_posts/2023-07-28-terraform-workshop.md
> +# Configure the Okta Terraform Provider
```suggestion
## Configure the Okta Terraform Provider
```

2023-07-28 19:39 UTC, edunham commented on _source/_posts/2023-07-28-terraform-workshop.md
> +title: "Okta Terraform Workshop"
```suggestion
title: "Enterprise-Ready Workshop: Terraform"
```

2023-07-28 20:39 UTC, edunham commented
for the tf expert feedback requirement, I ran it by Mike Mondragon, and integrated his Slack feedback into the post to address some common questions that beginners to Okta's Terraform ask

2023-07-28 21:29 UTC, cbeac243 requested changes

2023-07-28 21:29 UTC, cbeac243 commented on _source/_posts/2023-07-28-terraform-workshop.md
> +In keeping with the Terraform theme, this workshop's examples will create users for some plants and animals, and assign them to a garden group. The exercises will work just as well if you choose a di
```suggestion
In keeping with the Terraform theme, this workshop's examples will create users for some plants and animals, and assign them to a garden group. However, the exercises will work just as well if you choose a different theme, so feel free to customize your users and groups to keep things interesting. 
```

2023-07-28 21:29 UTC, cbeac243 commented on _source/_posts/2023-07-28-terraform-workshop.md
> +Notice how `<<` and a custom delimiter, in this case `POEM`, start the multi-line string. The same delimiter, in this case `POEM`, on its own line, ends the string.
```suggestion
Notice how `<<` and a custom delimiter, in this case `POEM`, start the multi-line string. The same delimiter, in this case, `POEM` on its own line ends the string. 
```

2023-07-28 21:43 UTC, palermo4 approved these changes

2023-07-28 21:44 UTC, merged

2023-07-28 22:18 UTC, isemona commented on _source/_posts/2023-07-28-terraform-workshop.md
> +* If your organization already uses Terraform to manageinfrastructure, learn about how terraform.tfstate files and secrets are managed.
```
suggestion
manageinfrastructure to manage infrastructure
```