Angular standalone app using runtime Okta config
oktadev/okta-blog pull request #1486
Opened 2024-02-23 20:05 UTC by alisaduncan

This blog post has the following features:

- [x] A GitHub Repository with a polished README
- [x] A GitHub Repository under the github.com/oktadev account
- [x] A title that's approved by Dev Advocacy
- [x] A URL approved by Dev Advocacy
- [x] The content has been run through Grammarly (https://www.grammarly.com/)
- [x] Rendered locally and confirmed that no Markdown typos exist
- [x] Images are compressed appropriately
- [x] Social image previews well on Twitter and LinkedIn
- [x] Tech review request (developer advocate or domain expert)
- [x] Review request for editorial/grammar/clarity (developer advocate or Colton)

2024-02-27 20:48 UTC, cbeac243 requested changes

2024-02-27 20:48 UTC, cbeac243 commented on _source/_posts/2024-02-28-okta-authentication-angular.md
> +Open `app.routes.ts`. Add the following routes.
```suggestion
Open `app.routes.ts`. Add the following routes:
```

2024-02-27 20:48 UTC, cbeac243 commented on _source/_posts/2024-02-28-okta-authentication-angular.md
> +We'll use the [Okta Angular](https://www.npmjs.com/package/@okta/okta-angular) and [Okta Auth JS](https://www.npmjs.com/package/@okta/okta-auth-js) libraries to connect our Angular application with O
```suggestion
We'll use the [Okta Angular](https://www.npmjs.com/package/@okta/okta-angular) and [Okta Auth JS](https://www.npmjs.com/package/@okta/okta-auth-js) libraries to connect our Angular application with Okta authentication. Add them to your project by running the following command:
```

2024-02-27 20:48 UTC, cbeac243 commented on _source/_posts/2024-02-28-okta-authentication-angular.md
> +You should see something like this when you start the application.
```suggestion
You should see something like this when you start the application:
```

2024-02-28 15:34 UTC, jaredperreault-okta approved these changes

2024-02-28 15:40 UTC, alisaduncan commented
Merging with Jared's approval.

2024-02-28 15:40 UTC, merged