DPoP overview
oktadev/okta-blog pull request #1525
Opened 2024-09-04 20:04 UTC by alisaduncan

This blog post has the following features:

- [x] A title that's approved by Dev Advocacy
- [x] A URL approved by Dev Advocacy
- [x] The content has been run through Grammarly (https://www.grammarly.com/)
- [x] Rendered locally and confirmed that no Markdown typos exist
- [x] Images are compressed appropriately
- [x] Social image previews well on Twitter and LinkedIn
- [x] Tech review request (developer advocate or domain expert)
- [x] Review request for editorial/grammar/clarity (developer advocate or Colton)

2024-09-04 21:11 UTC, coltonbeach requested changes

2024-09-04 21:11 UTC, coltonbeach commented on _source/_posts/2024-09-05-dpop-oauth.md
> +We use access tokens to request data and perform actions within our software systems. The client application sends a bearer token to the resource server. The resource server checks the validity of th
```suggestion
We use access tokens to request data and perform actions within our software systems. The client application sends a bearer token to the resource server. The resource server checks the validity of the access token before acting upon the HTTP request. What happens if the requesting party is malicious, steals your token, and makes a fraudulent API call? Would the resource server honor the HTTP request? If you use a bearer token, the answer is "yes." 
```

2024-09-04 21:11 UTC, coltonbeach commented on _source/_posts/2024-09-05-dpop-oauth.md
> +A sequence diagram for the OAuth 2.0 Authorization Code flow with DPoP looks like this.
```suggestion
A sequence diagram for the OAuth 2.0 Authorization Code flow with DPoP looks like this:
```

2024-09-04 22:04 UTC, edunham approved these changes
requested changes are completed

2024-09-05 16:27 UTC, coltonbeach approved these changes

2024-09-05 16:27 UTC, merged