Initial draft DPoP with Angular
oktadev/okta-blog pull request #1526
Opened 2024-09-05 18:47 UTC by alisaduncan

This blog post has the following features:

- [x] A GitHub Repository with a polished README
- [x] A GitHub Repository under the github.com/oktadev account
- [x] A title that's approved by Dev Advocacy
- [x] A URL approved by Dev Advocacy
- [x] The content has been run through Grammarly (https://www.grammarly.com/)
- [x] Rendered locally and confirmed that no Markdown typos exist
- [x] Images are compressed appropriately
- [ ] Social image previews well on Twitter and LinkedIn
- [x] Tech review request (developer advocate or domain expert)
- [x] Review request for editorial/grammar/clarity (developer advocate or Colton)

2024-09-05 19:32 UTC, coltonbeach requested changes

2024-09-05 19:32 UTC, coltonbeach commented on _source/_posts/2024-08-09-angular-dpop-jwt.md
> +We use OAuth 2.0 access tokens to request data and to perform actions within our software systems. A resource server first checks the validity of the access token before acting upon the HTTP request.
```suggestion
We use OAuth 2.0 access tokens to request data and to perform actions within our software systems. A resource server first checks the validity of the access token before acting upon the HTTP request. What happens if the requesting party is a malicious sort who stole your token? Would the resource server honor the HTTP request? If you use a bearer token, the answer is "yes." 
```

2024-09-05 19:32 UTC, coltonbeach commented on _source/_posts/2024-08-09-angular-dpop-jwt.md
> +**JAD TODO - Let's start with an application using OpenID Connect and OAuth 2.0** We're following best-practices, that is for this Angular app (a SPA) we're using authorization code flow with PKCE. C
```suggestion
**JAD TODO - Let's start with an application using OpenID Connect and OAuth 2.0** We're following best-practices, that is for this Angular app (a SPA) we're using authorization code flow with PKCE. Create the Okta developer account and get app going. Sign in following network calls and URL redirection requests. Use Org AS, and make a call to users API.
```

2024-09-05 19:32 UTC, coltonbeach commented on _source/_posts/2024-08-09-angular-dpop-jwt.md
> +If we go back to the hotel keycard example, what we want is a hotel keycard only you can use. Something that links you are the rightful user of the hotel keycard.
```suggestion
If we go back to the hotel keycard example, what we want is a hotel keycard only you can use; something that links you are the rightful user of the hotel keycard. 
```

2024-09-05 19:32 UTC, coltonbeach commented on _source/_posts/2024-08-09-angular-dpop-jwt.md
> +The methods to bind access tokens apply only to confidential clients, those that can maintain secrets. Which means the methods don't apply to public clients. Public clients are apps that run authenti
```suggestion
The methods to bind access tokens apply only to confidential clients, (those that can maintain secrets) which means the methods don't apply to public clients. Public clients are apps that run authentication code within the user's hardware, such as in Single-Page Applications (SPA) and mobile clients. Public clients are widely used with avenues for token security exploits without careful protection. Is there an alternative?
```

2024-09-05 19:32 UTC, coltonbeach commented on _source/_posts/2024-08-09-angular-dpop-jwt.md
> +When using DPoP, the client uses asymmetric encryption to create the proof. The DPoP proof is a JWT that includes the URI and the HTTP method of the request along with the public key. (The proof bind
```suggestion
When using DPoP, the client uses asymmetric encryption to create the proof. The DPoP proof is a JWT that includes the URI and the HTTP method of the request along with the public key. (The proof binds the HTTP request to alleviate overpowered malicious parties who steal tokens.)
```

2024-09-05 19:32 UTC, coltonbeach commented on _source/_posts/2024-08-09-angular-dpop-jwt.md
> +Now that token has possession proof, the tokens are no longer bearer tokens. Only the requesting client can use the token. Clients request resources by sending the access token along with a proof dem
```suggestion
Now that token has possession proof, the tokens are no longer bearer tokens. Only the requesting client can use the token. Clients request resources by sending the access token along with a proof demonstrating they are the legitimate holders of the access token to resource servers using a new scheme `DPoP`. Let's walk through the process:
```

2024-09-05 21:08 UTC, coltonbeach requested changes

2024-09-05 21:08 UTC, coltonbeach commented on _source/_posts/2024-09-10-angular-dpop-jwt.md
> +The high-level overview of DPoP uses public/private keys to create a signed DPoP proof that the authorization and resource server use to confirm the authenticity of the request and requesting client.
```suggestion
The high-level overview of DPoP uses public/private keys to create a signed DPoP proof that the authorization and resource server use to confirm the authenticity of the request and requesting client. This way, the token is sender-constrained, and a token thief is less likely to use a compromised access token. Learn more about the problems DPoP solves and how it works by reading:
```

2024-09-05 21:08 UTC, coltonbeach commented on _source/_posts/2024-09-10-angular-dpop-jwt.md
> +The primary use case for DPoP is for public clients, the applications where authentication code runs within the end user's browser, such as Single-Page Applications (SPA) and mobile apps. Due to thei
```suggestion
The primary use case for DPoP is for public clients, (the applications where authentication code runs within the end user's browser, such as Single-Page Applications (SPA) and mobile apps). Due to their architecture, public clients inherently have higher risk and less security in authentication and authorization. Public clients can't leverage a client secret used by application types that can communicate to the authorization server through a "back-channel," a network connection opaque to users, network sniffing attackers, and nosy developers. Without proper protection, a SPA may store tokens accessible to the end-user and injection-related attacks. DPoP adds an extra protection layer that makes tokens less usable if stolen.
```

2024-09-05 21:08 UTC, coltonbeach commented on _source/_posts/2024-09-10-angular-dpop-jwt.md
> +You'll use a starter project. The instructions are for the Angular sample project. If you are following along in [React](https://github.com/okta-samples/okta-react-sample) or [Vue](https://github.com
```suggestion
You'll use a starter project. These instructions are for the Angular sample project. If you are following along in [React](https://github.com/okta-samples/okta-react-sample) or [Vue](https://github.com/okta-samples/okta-vue-sample), replace the GitHub repo location with the URL for the sample you're using. 
```

2024-09-05 21:08 UTC, coltonbeach commented on _source/_posts/2024-09-10-angular-dpop-jwt.md
> +> Access tokens expire quickly. If too much time passes in these next steps, you may get a `401 Unauthorized`. If you do, repeat the steps with a more recent access token by navigating between the pr
```suggestion
> Access tokens expire quickly. If too much time passes in these next steps, you may get a `401 Unauthorized`. If you do, repeat the steps with a more recent access token by navigating between the profile and user routes to trigger a call to the API. It prompts the OIDC client (the Okta Auth JS SDK) to update expired tokens.
```

2024-09-05 21:08 UTC, coltonbeach commented on _source/_posts/2024-09-10-angular-dpop-jwt.md
> +The call succeeds even though the client making the call, your HTTP client, isn't the same client the authorization issued the token to, the sample app.
```suggestion
The call succeeds even though the client making the call (your HTTP client) isn't the same client the authorization issued the token to, the sample app.
```

2024-09-05 21:08 UTC, coltonbeach commented on _source/_posts/2024-09-10-angular-dpop-jwt.md
> +The call succeeds even though the client making the call, your HTTP client, isn't the same client the authorization issued the token to, the sample app.
```suggestion
The call succeeds even though the client making the call, your HTTP client, isn't the same client the authorization issued the token to (the sample app).
```

2024-09-05 21:08 UTC, coltonbeach commented on _source/_posts/2024-09-10-angular-dpop-jwt.md
> +The call succeeds even though you call from a different client, like you saw in the prior step, calling the Users API. The call succeeds for a privileged user as long as the Okta Application has the
```suggestion
The call succeeds even though you call from a different client, like you saw in the prior step, calling the Users API. The call succeeds for a privileged user as long as the Okta Application has the `okta.apps.read` and the OIDC config has the scope. You may say that's a lot of constraints, and you're right. Okta adds a lot of guards when making API requests about the resources in the top-level Okta org, such as the list of Okta applications. This example demonstrates how powerful and vulnerable a privileged user (such as an admin access) is. Anyone with the token can make the same request, even if they are an attacker.
```

2024-09-05 21:08 UTC, coltonbeach commented on _source/_posts/2024-09-10-angular-dpop-jwt.md
> +It doesn't matter if your application uses bearer tokens or DPoP; apps must employ secure coding practices. DPoP doesn't prevent attackers from stealing your token but constrains its use. DPoP uses a
```suggestion
It doesn't matter if your application uses bearer tokens or DPoP; apps must employ secure coding practices. DPoP doesn't prevent attackers from stealing your token but constrains its use. DPoP uses asymmetric encryption to prove token ownership, so you must avoid exfiltration or unauthorized use of the keyset. If an attacker gets a hold of the private key they can create valid proofs.
```

2024-09-05 21:08 UTC, coltonbeach commented on _source/_posts/2024-09-10-angular-dpop-jwt.md
> +All HTTP requests to DPoP-protected resources, including the `/token` request to sign in, now require a DPoP proof. We must enable DPoP in the OIDC configuration.
```suggestion
All HTTP requests to DPoP-protected resources (including the `/token` request to sign in) now require a DPoP proof. We must enable DPoP in the OIDC configuration.
```

2024-09-06 14:05 UTC, alisaduncan commented on _source/_posts/2024-09-10-angular-dpop-jwt.md
> +The primary use case for DPoP is for public clients, the applications where authentication code runs within the end user's browser, such as Single-Page Applications (SPA) and mobile apps. Due to thei
I think I'll split this into 2 sentences

2024-09-06 14:06 UTC, alisaduncan commented on _source/_posts/2024-09-10-angular-dpop-jwt.md
> +The call succeeds even though the client making the call, your HTTP client, isn't the same client the authorization issued the token to, the sample app.
I'll reword this sentence entirely

2024-09-06 14:07 UTC, alisaduncan commented on _source/_posts/2024-09-10-angular-dpop-jwt.md
> +The call succeeds even though you call from a different client, like you saw in the prior step, calling the Users API. The call succeeds for a privileged user as long as the Okta Application has the
Rewording

2024-09-06 14:08 UTC, alisaduncan commented on _source/_posts/2024-09-10-angular-dpop-jwt.md
> +All HTTP requests to DPoP-protected resources, including the `/token` request to sign in, now require a DPoP proof. We must enable DPoP in the OIDC configuration.
rewording

2024-09-06 16:16 UTC, coltonbeach approved these changes

2024-09-10 15:17 UTC, merged