Update 2024-02-29-third-party-cookies.md
oktadev/okta-blog pull request #1535
Opened 2024-09-30 20:04 UTC by edunham

This blog post has the following features:

- [ ] A GitHub Repository with a polished README
- [ ] A GitHub Repository under the github.com/oktadev account
- [ ] A title that's approved by Dev Advocacy
- [ ] A URL approved by Dev Advocacy
- [ ] The content has been run through Grammarly (https://www.grammarly.com/)
- [ ] Rendered locally and confirmed that no Markdown typos exist
- [ ] Images are compressed appropriately
- [ ] Social image previews well on Twitter and LinkedIn
- [ ] Tech review request (developer advocate or domain expert)
- [ ] Review request for editorial/grammar/clarity (developer advocate or Colton)

2024-10-01 15:30 UTC, alisaduncan requested changes

2024-10-01 15:30 UTC, alisaduncan commented on _source/_posts/2024-02-29-third-party-cookies.md
> +**NOTE**: In July, Google has given an update on their [3rd party cookie deprecation effort](https://developers.google.com/privacy-sandbox/cookies).  Okta will be working with Google to understand th
Please ensure "third-party cookie" is used consistently.

2024-10-01 15:30 UTC, alisaduncan commented on _source/_posts/2024-02-29-third-party-cookies.md
> +**NOTE**: In July, Google has given an update on their [3rd party cookie deprecation effort](https://developers.google.com/privacy-sandbox/cookies).  Okta will be working with Google to understand th
Also ensure punctuation (missing period).

2024-10-01 19:29 UTC, edunham commented on _source/_posts/2024-02-29-third-party-cookies.md
> +**NOTE**: In July, Google has given an update on their [3rd party cookie deprecation effort](https://developers.google.com/privacy-sandbox/cookies).  Okta will be working with Google to understand th
```suggestion
**NOTE**: In July, Google has given an update on their [third-party cookie deprecation effort](https://privacysandbox.com/news/privacy-sandbox-update/).  Okta will be working with Google to understand the specific impact to Okta customers.  In the meantime, we continue to advise customers to migrate way from the use of 3rd party cookies, as outlined below.
```

2024-10-01 19:33 UTC, alisaduncan requested changes
Ran through Grammarly and noticed typos

2024-10-01 19:33 UTC, alisaduncan commented on _source/_posts/2024-02-29-third-party-cookies.md
> +**NOTE**: In July, Google has given an update on their [third-party cookie deprecation effort](https://privacysandbox.com/news/privacy-sandbox-update/).  Okta will be working with Google to understan
```suggestion
**NOTE**: In July, Google provided an update on their [third-party cookie deprecation effort](https://privacysandbox.com/news/privacy-sandbox-update/). Okta will work with Google to understand the specific impact on Okta customers. In the meantime, we continue to advise customers to migrate away from using 3rd party cookies, as outlined below.
```

2024-10-01 22:10 UTC, edunham commented on _source/_posts/2024-02-29-third-party-cookies.md
> +**NOTE**: In July, Google provided an update on their [third-party cookie deprecation effort](https://privacysandbox.com/news/privacy-sandbox-update/). Okta will work with Google to understand the sp
```suggestion
**NOTE**: In July, Google provided an update on their [third-party cookie deprecation effort](https://privacysandbox.com/news/privacy-sandbox-update/). Okta will work with Google to understand the specific impact on Okta customers. In the meantime, we continue to advise customers to migrate away from using third-party cookies, as outlined below.
```

2024-10-02 12:19 UTC, alisaduncan approved these changes

2024-10-02 14:59 UTC, merged