Initial commit
oktadev/okta-blog pull request #1538
Opened 2024-10-04 20:28 UTC by alisaduncan

This blog post has the following features:

- [x] A GitHub Repository with a polished README
- [x] A GitHub Repository under the github.com/oktadev account
- [x] A title that's approved by Dev Advocacy
- [x] A URL approved by Dev Advocacy
- [x] The content has been run through Grammarly (https://www.grammarly.com/)
- [x] Rendered locally and confirmed that no Markdown typos exist
- [x] Images are compressed appropriately
- [x] Social image previews well on Twitter and LinkedIn
- [ ] Tech review request (developer advocate or domain expert)
- [ ] Review request for editorial/grammar/clarity (developer advocate or Colton)

2024-10-07 17:33 UTC, ramgandhi-okta commented on _source/_posts/2024-10-02-dpop-oauth-node.md
> +    * `oktaHelper` contains utility methods to store okta configuration, access token, generating private key JWT, generating token request
The indentation should be changed since this is not coming as a separate bullet point in the preview.

2024-10-22 13:56 UTC, coltonbeach requested changes

2024-10-22 13:56 UTC, coltonbeach commented on _source/_posts/2024-10-24-dpop-oauth-node.md
> +Add a new file named `app.js` in the project root folder. This is the entry point for running our Node.js service application. In this file, we'll do the following
```suggestion
Add a new file named `app.js` in the project root folder. This is the entry point for running our Node.js service application. In this file, we'll do the following:
```

2024-10-22 13:56 UTC, coltonbeach commented on _source/_posts/2024-10-24-dpop-oauth-node.md
> +Next, update this as the entry point. In the `package.json` file, update the `scripts` property with the following.
```suggestion
Next, update this as the entry point. In the `package.json` file, update the `scripts` property with the following:
```

2024-10-22 13:56 UTC, coltonbeach commented on _source/_posts/2024-10-24-dpop-oauth-node.md
> +Our setup used the `client_credentials` grant type to authenticate and get an access token. If someone gets hold of the private_key_jwt, they cannot replay it beyond expiration (I reduced it to 5 min
```suggestion
Our setup used the `client_credentials` grant type to authenticate and get an access token. If someone gets hold of the private_key_jwt, they cannot replay it beyond expiration (I reduced it to 5 minutes to shorten this window). However, if someone gets ahold of the access token, they can use it for up to 1 hour, which is the default expiration time of an access token. 
```

2024-10-22 13:56 UTC, coltonbeach commented on _source/_posts/2024-10-24-dpop-oauth-node.md
> +Constraining the token sender is one way to make the access token more secure. How can you do that? By adding the Demonstrating Proof of Possession (DPoP) OAuth extension method to the access token i
```suggestion
Constraining the token sender is one way to make the access token more secure. How can you do that? By adding the Demonstrating Proof of Possession (DPoP) OAuth extension method to the access token interaction. The technique adds a sender-generated token for each call it makes. Doing so prevents replay attacks even before tokens expire since each call needs a fresh DPoP token. Here is the detailed flow:
```

2024-10-22 13:56 UTC, coltonbeach commented on _source/_posts/2024-10-24-dpop-oauth-node.md
> +Add the DPoP-related code to `oktaService.js`. Add the key files to config; we can use this while adding DPoP to our methods
```suggestion
Add the DPoP-related code to `oktaService.js`. Add the key files to config. We can use this while adding DPoP to our methods:
```

2024-10-22 16:08 UTC, coltonbeach approved these changes

2024-10-23 16:07 UTC, merged