Revert "Oktane promo banner (#1532)"
oktadev/okta-blog pull request #1542
Opened 2024-10-29 19:59 UTC by edunham

This reverts commit 1211b97a71e259bd1601a363769b8503884f5ffa.

This blog post has the following features:

- [ ] A GitHub Repository with a polished README
- [ ] A GitHub Repository under the github.com/oktadev account
- [ ] A title that's approved by Dev Advocacy
- [ ] A URL approved by Dev Advocacy
- [ ] The content has been run through Grammarly (https://www.grammarly.com/)
- [ ] Rendered locally and confirmed that no Markdown typos exist
- [ ] Images are compressed appropriately
- [ ] Social image previews well on Twitter and LinkedIn
- [ ] Tech review request (developer advocate or domain expert)
- [ ] Review request for editorial/grammar/clarity (developer advocate or Colton)

2024-10-29 20:03 UTC, isemona approved these changes

2024-10-29 20:19 UTC, alisaduncan requested changes
Instead of reverting the PR, can we just hide the banner please?

2024-10-29 20:36 UTC, alisaduncan reviewed
Changing to comment so it doesn't block merge, but respectfully requesting changing the flag instead of reverting the PR.

2024-10-29 20:40 UTC, edunham commented on _source/_includes/promo_banner.html
> +  <a href="https://regionalevents.okta.com/enterprisereadyworkshops" class="DocsPromoBanner">
```suggestion
  <a href="/blog/2024/09/26/oktane-saas-developers" class="DocsPromoBanner">
```

2024-10-29 20:41 UTC, edunham commented on _source/_includes/promo_banner.html
> +      <span class="promo-body">Check out the free virtual workshops on how to take your SaaS app to the next level in the enterprise-ready identity journey!</span>
```suggestion
      <span class="promo-body">See you at Oktane in Las Vegas on October 15-17, 2024. Read more about the activities planned with you mind here.</span>
```

2024-10-29 20:55 UTC, edunham commented
swapped it over to just hide the banner. I'd assumed we might want to resume promo on the workshops soonish, but I have no objections to leaving the rest in the oktane promo state for now.

2024-10-30 12:45 UTC, alisaduncan approved these changes

2024-10-31 16:40 UTC, merged

2024-10-31 16:41 UTC, isemona commented
confirmed with @edunham good to close