Add Xinxin Zhu to authors.yml
oktadev/okta-blog pull request #840
Opened 2021-07-29 12:06 UTC by starsz

This blog post has the following features:

- [ ] A GitHub Repository with a polished README
- [ ] A GitHub Repository under the github.com/oktadev account
- [ ] A title that's approved by Dev Advocacy
- [ ] A URL that's approved by Dev Advocacy
- [ ] The content has been ran through Grammarly (https://www.grammarly.com/)
- [ ] Rendered locally and confirmed that no Markdown typos exist

2021-07-30 07:38 UTC, yzeng25 requested changes

2021-07-30 07:38 UTC, yzeng25 commented on _source/_data/authors.yml
> +    a golang fans. Now, he is working on control plane of Apache APISIX such as writing code, reviewing code and answering questions
fans --> fan

2021-07-30 07:38 UTC, yzeng25 commented on _source/_data/authors.yml
> +    he is a very funny persion. :)
he is a fun guy.

Funny  and fun have slightly difference. Fun means "有趣", funny means "滑稽".

2021-07-30 07:57 UTC, starsz commented on _source/_data/authors.yml
> +    a golang fans. Now, he is working on control plane of Apache APISIX such as writing code, reviewing code and answering questions
Fix. Use developer instead.

2021-07-30 07:57 UTC, starsz commented on _source/_data/authors.yml
> +    he is a very funny persion. :)
Fixed.

2021-07-30 07:58 UTC, yzeng25 approved these changes

2021-07-30 15:43 UTC, bdemers commented on _source/_data/authors.yml
> +    he is a fun guy. :)
```suggestion
    Xinxin Zhu is a System Engineer at API7.AI and a committer for the Apache APISIX project. He is an open-source enthusiast and
    a Golang developer. Now, he is working on the control plane of Apache APISIX writing code, reviewing code, and answering questions
    in the community. Xinxin Zhu is a fun guy, you can find him on Twitter at <a href="https://twitter.com/starszcan">@starszcan</a> 🙂
```

2021-07-30 15:45 UTC, bdemers approved these changes
Thanks!! This is great!

2021-08-01 15:21 UTC, starsz commented
> Thanks!! This is great!

Much appreciated!

2021-08-17 20:42 UTC, bdemers approved these changes

2021-08-17 21:34 UTC, merged