[2021-08-05] Libsodium post
oktadev/okta-blog pull request #846
Opened 2021-08-04 17:19 UTC by bdemers

This blog post has the following features:

- [ ] A GitHub Repository with a polished README
- [x] A GitHub Repository under the github.com/oktadev account
- [x] A title that's approved by Dev Advocacy
- [x] A URL that's approved by Dev Advocacy
- [x] The content has been ran through Grammarly (https://www.grammarly.com/)
- [x] Rendered locally and confirmed that no Markdown typos exist

2021-08-04 20:05 UTC, havi commented on _source/_posts/2021-08-05-libsodium-encryption-go-python.md
> +Today, we will use `libsodium` for Python to encrypt messages and decrypt them using `libsodium` in Go. Let's get started!
is there any specific reason why you switched prepositions ("for Python" vs "in Go")? I would tend to keep it consistent within the sentence (for, for) or (in, in), but maybe there's a nuance i'm missing?, or maybe it was grammarly's lame suggestion...? Optional tweak. Not a hard edit.

2021-08-04 21:01 UTC, havi commented on _source/_posts/2021-08-05-libsodium-encryption-go-python.md
> +Secret key encryption uses a single key to both encrypt and decrypt a message. It is commonly used as a faster alternative to public-key encryption. The key itself is a fixed-length random number. As
```suggestion
Secret-key encryption uses a single key to both encrypt and decrypt a message. It is commonly used as a faster alternative to public-key encryption. The key itself is a fixed-length random number. As there is only a single key, both the sender and recipient need a copy of it. This requires a key exchange which is often performed out of band or by using public-key encryption.
```

for consistency.

2021-08-04 21:02 UTC, havi commented on _source/_posts/2021-08-05-libsodium-encryption-go-python.md
> +We will again encrypt the poem Jabberwocky, but this time using secret key encryption. For convenience, we will again generate and store the key in a file:
```suggestion
We will again encrypt the poem Jabberwocky, but this time using secret-key encryption. For convenience, we will again generate and store the key in a file:
```
consistency

2021-08-04 21:21 UTC, havi commented on _source/_posts/2021-08-05-libsodium-encryption-go-python.md
> +The message to be encrypted is a text file containing the poem *Jabberwocky* by Lewis Carroll. The poem itself is somewhat cryptic, as the meaning of the words is open to interpretation! Rather fitti
```suggestion
The message to be encrypted is a text file containing the poem "Jabberwocky" by Lewis Carroll. The poem itself is somewhat cryptic, as the meaning of the words is open to interpretation! Rather fittingly, Jabberwocky was first published in the book *Through the Looking-Glass, and What Alice Found There*.
```
double-quotes

2021-08-04 21:22 UTC, havi commented on _source/_posts/2021-08-05-libsodium-encryption-go-python.md
> +Download the Jabberwocky poem to `jabberwocky.txt`:
```suggestion
Download the "Jabberwocky" poem to `jabberwocky.txt`:
```
double-quotes

2021-08-04 21:23 UTC, havi commented on _source/_posts/2021-08-05-libsodium-encryption-go-python.md
> +Run the application to see the poem Jabberwocky restored:
```suggestion
Run the application to see the poem "Jabberwocky" restored:
```

double-quotes

2021-08-04 21:24 UTC, havi commented on _source/_posts/2021-08-05-libsodium-encryption-go-python.md
> +We will again encrypt the poem Jabberwocky, but this time using secret key encryption. For convenience, we will again generate and store the key in a file:
```suggestion
We will again encrypt the poem "Jabberwocky," but this time using secret-key encryption. For convenience, we will again generate and store the key in a file:
```
double-quotes and hyphenate secret-key encryption

2021-08-04 21:25 UTC, havi commented on _source/_posts/2021-08-05-libsodium-encryption-go-python.md
> +Run the program to see the Jabberwocky poem restored:
```suggestion
Run the program to see the "Jabberwocky" poem restored:
```

2021-08-04 21:38 UTC, havi requested changes
with double quotes to all the Jabberwocky instances, and tweaked a couple other small bits.

2021-08-05 00:11 UTC, bdemers commented on _source/_posts/2021-08-05-libsodium-encryption-go-python.md
> +Today, we will use `libsodium` for Python to encrypt messages and decrypt them using `libsodium` in Go. Let's get started!
```suggestion
Today, we will use `libsodium` in Python to encrypt messages and decrypt them using `libsodium` in Go. Let's get started!
```

2021-08-05 00:12 UTC, bdemers commented on _source/_posts/2021-08-05-libsodium-encryption-go-python.md
> +We will again encrypt the poem Jabberwocky, but this time using secret key encryption. For convenience, we will again generate and store the key in a file:
```suggestion
We will again encrypt the poem Jabberwocky, but this time using secret-key encryption. For convenience, we will again generate and store the key in a file:
```

2021-08-05 14:33 UTC, havi approved these changes

2021-08-05 18:34 UTC, merged