Nico blog secure access to eks
oktadev/okta-blog pull request #914
Opened 2021-10-07 18:17 UTC by nickgamb

Initial commit

This blog post has the following features:

- [X] A GitHub Repository with a polished README
- [X] A GitHub Repository under the github.com/oktadev account
- [X] A title that's approved by Dev Advocacy
- [X] A URL that's approved by Dev Advocacy
- [X] The content has been ran through Grammarly (https://www.grammarly.com/)
- [X] Rendered locally and confirmed that no Markdown typos exist

2021-10-07 22:43 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +description: "Secure Access to AWS EKS Clusters with Okta."
```suggestion
description: "This tutorial is a step-by-step guide for admins on how to implement secure access to AWS EKS Clusters with Okta."
```
adding more description on type of article

2021-10-07 23:01 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +This tutorial will show you how to leverage OIDC to securely access Amazon Elastic Kubernetes Service (EKS) clusters. It's intended for AWS DevOps and Identity Security administrator teams, Anyone wi
```suggestion
This tutorial is intended to show AWS DevOps and Identity Security administrator teams how to securely access securely access Amazon Elastic Kubernetes Service (EKS) clusters.  Anyone with an interest in Identity Security best practices can learn from this guide, but it assumes at least some knowledge of:
```
paring it down, since it's kind of a repeat of line 27

2021-10-07 23:02 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +-   Terminal on a end-user workstation (e.g. MacOS, Windows, Linux)
```suggestion
-   Terminal on a end-user workstation (e.g. macOS, Windows, Linux)
```
brand spelling

2021-10-07 23:34 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +Note: We recommend configuring [access to the AWS Console using Okta SSO+MFA](https://docs.aws.amazon.com/singlesignon/latest/userguide/okta-idp.html)
```suggestion
Note: We recommend configuring [access to the AWS Console using Okta SSO+MFA](https://docs.aws.amazon.com/singlesignon/latest/userguide/okta-idp.html).
```
punctuation

2021-10-07 23:46 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +On the next screen, copy the **Issuer URL** from the Settings tab. We'll need it later:
```suggestion
On the next screen, copy the **Issuer URL** from the **Settings** tab. We'll need it later:
```
bolding

2021-10-07 23:47 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +-   Go to the **Claims** tab and select**Add Claim**.
```suggestion
-   Go to the  **Claims** tab and select**Add Claim**.
```
space

2021-10-08 03:21 UTC, nickgamb commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +-   Terminal on a end-user workstation (e.g. MacOS, Windows, Linux)
Manually Added

2021-10-08 03:21 UTC, nickgamb commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +This tutorial will show you how to leverage OIDC to securely access Amazon Elastic Kubernetes Service (EKS) clusters. It's intended for AWS DevOps and Identity Security administrator teams, Anyone wi
Manually Added

2021-10-08 03:22 UTC, nickgamb commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +Note: We recommend configuring [access to the AWS Console using Okta SSO+MFA](https://docs.aws.amazon.com/singlesignon/latest/userguide/okta-idp.html)
Manually Added

2021-10-08 03:23 UTC, nickgamb commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +On the next screen, copy the **Issuer URL** from the Settings tab. We'll need it later:
Manually Added

2021-10-08 03:23 UTC, nickgamb commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +-   Go to the **Claims** tab and select**Add Claim**.
Manually Added

2021-10-08 11:08 UTC, deepu105 reviewed
Looks great overall. I made some minor suggestions.

2021-10-08 11:08 UTC, deepu105 commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +In this tutorial, we will leverage [OpenID Connect](https://www.okta.com/openid-connect/) (OIDC) to allow our DevOps team to securely access their EKS clusters on AWS. We use  [Role Based Access Cont
```suggestion
In this tutorial, we will leverage [OpenID Connect](https://www.okta.com/openid-connect/) (OIDC) to allow our DevOps team to securely access their EKS clusters on AWS. We use  [Role Based Access Control (RBAC)](https://www.okta.com/identity-101/what-is-role-based-access-control-rbac/)] to enforce the least privilege required without the need to configure AWS IAM roles. 😎
```
removed extra space

2021-10-08 11:08 UTC, deepu105 commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +In this tutorial, we will leverage [OpenID Connect](https://www.okta.com/openid-connect/) (OIDC) to allow our DevOps team to securely access their EKS clusters on AWS. We use  [Role Based Access Cont
IMO this makes it clearer

2021-10-08 11:08 UTC, deepu105 commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +This tutorial is intended to show AWS DevOps and Identity Security administrator teams how to securely access securely access Amazon Elastic Kubernetes Service (EKS) clusters.  Anyone with an interes
```suggestion
This tutorial is intended to show AWS DevOps and Identity Security administrator teams how to securely access Amazon Elastic Kubernetes Service (EKS) clusters. Anyone with an interest in Identity Security best practices can learn from this guide, but it assumes at least some knowledge of:
```

2021-10-08 11:08 UTC, deepu105 commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +-   k8s, API Server, RBAC Authorization, role binding
```suggestion
-   Kubernetes (k8s),  k8s API Server, k8s RBAC Authorization, and k8s role binding
```

2021-10-08 11:08 UTC, deepu105 commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +Okta, Inc. is an identity and access management company, providing cloud software that helps companies manage and secure user authentication into applications, and for developers to build identity co
shouldn't it be "websites, web services"
```suggestion
Okta, Inc. is an identity and access management company, providing cloud software that helps companies manage and secure user authentication into applications, and for developers to build identity controls into applications, websites, web services, and devices. You get scalable authentication built right into your application without the development overhead, security risks, and maintenance that come from building it yourself.
```

2021-10-08 11:08 UTC, deepu105 commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +Kubernetes, also known by the abbreviation k8s, is an open-source system for automating deployment, scaling, and management of containerized applications. See  [https://kubernetes.io/](https://kubern
```suggestion
Kubernetes, also known by the abbreviation k8s, is an open-source container orchestration platform for automating deployment, scaling, and management of containerized applications. See  [https://kubernetes.io/](https://kubernetes.io/). 
```

2021-10-08 11:08 UTC, deepu105 commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +Your EKS cluster will take a couple of minutes to start. In the meantime, let's do the configuration on the Okta side.Then we'll come back to the AWS Console to configure Okta as the OIDC provider fo
```suggestion
Your EKS cluster will take a couple of minutes to start. In the meantime, let's do the configuration on the Okta side. Then we'll come back to the AWS Console to configure Okta as the OIDC provider for the EKS cluster.
```

2021-10-08 11:08 UTC, deepu105 commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +In the Okta admin console, we'll create a group of users that we'll assign to a OIDC client, and we'll configure the AuthZ Server to inject the list of groups into the id_token.
can we link the admin console URL

2021-10-08 11:08 UTC, deepu105 commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +Now let's add a custom claim "groups" in the id_token that Okta will generate, to list the groups of the connected user.
should the word `id_token` be formatted using code or something? it appears many times

2021-10-08 11:08 UTC, deepu105 commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +This basically specifies the config of the OIDC provider. Note: Replace the `oidc-issuer-url` and `oidc-client-id` with your own values.
```suggestion
This basically specifies the config of the OIDC provider. Note: Replace the `oidc-issuer-url` and `oidc-client-id` with Issuer URL and Client ID we copied earlier.
```

2021-10-08 11:08 UTC, deepu105 commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +- Delete any existing config files and add the one from CloudShell:
```suggestion
- Rename any existing config files as a backup and add the one from CloudShell:
```

2021-10-08 11:08 UTC, deepu105 commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +- Double-check that the current context is properly set.
```suggestion
You may want to adjust the context name in the above command based on the context name in your own config file.

- Double-check that the current context is properly set.
```

2021-10-08 11:08 UTC, deepu105 commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +- Install [kubelogin](https://github.com/int128/kubelogin)  (the OIDC helper for kubectl)
```suggestion
- Install [kubelogin](https://github.com/int128/kubelogin)  (the OIDC helper for kubectl). Run this for mac/Linux:
```

2021-10-08 14:54 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +by: advocate
```suggestion
by: internal-contributor
```

2021-10-08 15:01 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +Now let's add a custom claim "groups" in the id_token that Okta will generate, to list the groups of the connected user.
```suggestion
Now let's add a custom claim "groups" in the `id_token` that Okta will generate, to list the groups of the connected user.
```

2021-10-08 15:01 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +- Use the following settings to add the groups claim in the id_token:
```suggestion
- Use the following settings to add the groups claim in the `id_token`:
```
code formatting

2021-10-08 15:02 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +- Now let's create an access policy on this AuthZ Server to drive when the AuthZ Server should mint the id_token.
```suggestion
- Now let's create an access policy on this AuthZ Server to drive when the AuthZ Server should mint the `id_token`.
```
code formatting

2021-10-08 15:03 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +Now let's run a test to see what our id_token will look like when the Okta AuthZ Server mints it.
```suggestion
Now let's run a test to see what our `id_token` will look like when the Okta AuthZ Server mints it.  
```
code formatting

2021-10-08 15:03 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +- Then click on **Token Preview**. On the right side of the screen, you'll  see a preview of your id_token. So far it has all the claims we're looking for, including:
```suggestion
- Then click on **Token Preview**. On the right side of the screen, you'll  see a preview of your `id_token`. So far it has all the claims we're looking for, including:
```

2021-10-08 15:03 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +- Configure a kubectl OIDC plugin to prompt the user for AuthN and request an id_token. We'll use [kubelogin](https://github.com/int128/kubelogin).
```suggestion
- Configure a kubectl OIDC plugin to prompt the user for AuthN and request an `id_token`. We'll use [kubelogin](https://github.com/int128/kubelogin).
```

2021-10-08 15:04 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +- Check your terminal. You should see a confirmation that you've received an id_token from Okta:
```suggestion
- Check your terminal. You should see a confirmation that you've received an `id_token` from Okta:
```

2021-10-08 15:06 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +- Then, let's delete the cached id_token on our laptop.
```suggestion
- Then, let's delete the cached `id_token` on our laptop.
```

2021-10-08 15:07 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +- That first file contains the id_token Okta minted. Let's delete it.
```suggestion
- That first file contains the `id_token` Okta minted. Let's delete it.
```

2021-10-08 15:07 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +As expected, we're not authorized. Since we're no longer a member of the eks-admins Okta group, the group is no longer injected in the id_token, and the Kubernetes API Server no longer applies the cl
```suggestion
As expected, we're not authorized. Since we're no longer a member of the eks-admins Okta group, the group is no longer injected in the `id_token`, and the Kubernetes API Server no longer applies the cluster-admin role.
```

2021-10-08 15:08 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +- Once again, let's delete the cached id_token in the `~/.kube/cache/oidc-login` folder.
```suggestion
- Once again, let's delete the cached `id_token` in the `~/.kube/cache/oidc-login` folder. 
```

2021-10-08 15:08 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +-   leverage an OIDC plugin that 1) prompts the user for AuthN in the web browser and 2) retrieves the [JSON Web Token  (JWT)](/blog/2020/12/21/beginners-guide-to-jwt) id_token from Okta and passes i
```suggestion
-   leverage an OIDC plugin that 1) prompts the user for AuthN in the web browser and 2) retrieves the [JSON Web Token  (JWT)](/blog/2020/12/21/beginners-guide-to-jwt) `id_token` from Okta and passes it to our [kubectl (Kubernetes command-line tool)](https://kubernetes.io/docs/tasks/tools/) commands
```

2021-10-08 15:09 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +In the Okta admin console, we'll create a group of users that we'll assign to a OIDC client, and we'll configure the AuthZ Server to inject the list of groups into the id_token.
```suggestion
In the Okta admin console, we'll create a group of users that we'll assign to a OIDC client, and we'll configure the AuthZ Server to inject the list of groups into the `id_token`.
```

2021-10-08 15:17 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +### Create a new EKS cluster
```suggestion
### Create a New EKS Cluster
```
title case for heading

2021-10-08 15:20 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +-  Select **Sign-in method OIDC - OpenID Connect**", **Application type Native Application**, then click Next:
```suggestion
-  Select **Sign-in method OIDC - OpenID Connect**, **Application type Native Application**, then click Next:
```
removed extra quotation mark

2021-10-08 15:22 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +-   In the **General** tab, be sure to select **Use PKCE**. Then copy the client id, we'll need it later:
```suggestion
-   In the **General** tab, be sure to select **Use PKCE**. Then copy the **Client ID**, we'll need it later:
```

2021-10-08 15:28 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +- Install kubectl on your local machine. (See the [instructions to install kubectl on MacOS](https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/)).
```suggestion
- Install kubectl on your local machine. (See the [instructions to install kubectl on macOS](https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/)).
```

2021-10-08 15:42 UTC, havi commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +- "TweetStuff!"
```suggestion
"This tutorial shows how to use #OIDC with #Okta to securely access EKS clusters on AWS #kubernetes #k8s #devops" #EKS 
```
tweet

2021-10-08 15:50 UTC, havi requested changes
I incorporated Deepu's changes and added a few final ones of my own into a batch. This awaits an approval.

2021-10-08 18:40 UTC, nickgamb commented on _source/_posts/2021-10-08-secure-access-to-aws-eks.md
> +- "TweetStuff!"
Had to remove hashtag because it causes front matter validation to fail

2021-10-08 19:17 UTC, havi approved these changes
Ship it!

2021-10-08 19:22 UTC, merged