Add security headers best practices post
oktadev/okta-blog pull request #922
Opened 2021-10-14 19:04 UTC by mraible

This blog post has the following features:

- [x] A title that's approved by Dev Advocacy
- [x] A URL that's approved by Dev Advocacy
- [x] The content has been run through Grammarly (https://www.grammarly.com/)
- [x] Rendered locally and confirmed that no Markdown typos exist

2021-10-14 19:53 UTC, mraible commented
@havi Looking at the TOC for this post, it seems like it might be able to have a wrap up header at the end.

2021-10-15 16:00 UTC, havi commented on _source/_posts/2021-10-18-security-headers-best-practices.md
> +### Strict Transport Security
```suggestion
### HTTP Strict Transport Security (HSTS)
```
following the OWASP usage

2021-10-15 16:02 UTC, havi commented on _source/_posts/2021-10-18-security-headers-best-practices.md
> +### Content-Security-Policy
```suggestion
### Content-Security-Policy (CSP) 
```
including the acronym

2021-10-15 16:05 UTC, havi commented on _source/_posts/2021-10-18-security-headers-best-practices.md
> +X-XSS-Protection: 1; mode=block (Turns on XSS Auditor, prevent rendering the page when an attack is detected)
```suggestion
X-XSS-Protection: 1; mode=block (Turns on XSS Auditor, prevents rendering the page when an attack is detected)
```
verb grammar

2021-10-15 17:13 UTC, havi commented on _source/_posts/2021-10-18-security-headers-best-practices.md
> +The Referrer-Policy header tells the browser when to send Referrer information. This can help prevent information leakages offsite via Referrer URLs. There are many options for this header, the most
```suggestion
The Referrer-Policy header tells the browser when to send Referrer information. This can help prevent information leakages offsite via Referrer URLs. There are many options for this header, the most useful ones being no-referrer, origin, origin-when-cross-origin, and same-origin. Note that ["referrer" is not misspelled in this header](https://en.wikipedia.org/wiki/HTTP_referer)!
```
adding link for context & clarity

2021-10-15 18:41 UTC, havi commented on _source/_posts/2021-10-18-security-headers-best-practices.md
> +There are many different directives of the policy, but the most important one is "script-src", which defines where scripts can be loaded from. Other directives include "default-src", "object-src", "i
" one is "script-src", which defines where scripts can be loaded from. Other directives include "default-src", "object-src", "img-src", "

Would these headers be more readable if code-formatted instead of double-quotes?

2021-10-15 18:44 UTC, havi commented on _source/_posts/2021-10-18-security-headers-best-practices.md
> +This header prevents MIME-sniffing. MIME-sniffing is when browsers try to determine the the document's file type by examining its content and disregarding the server's instructions set in the Content
```suggestion
This header prevents MIME-sniffing. MIME-sniffing is when browsers try to determine the document's file type by examining its content and disregarding the server's instructions set in the Content-Type header.
```
typo the

2021-10-15 18:45 UTC, havi commented on _source/_posts/2021-10-18-security-headers-best-practices.md
> +MIME-sniffing is a useful feature but can lead to vulnerabilities. For example, an attacker can upload a JavaScript file with the extension of an image file. When others try to view the image, their
```suggestion
MIME-sniffing is a useful feature but can lead to vulnerabilities. For example, an attacker can upload a JavaScript file with the extension of an image file. When others try to view the image, their browsers detect that the file is a JavaScript file and execute it instead of rendering it as an image. Setting this header to "nosniff" will prevent MIME-sniffing.
```
grammar

2021-10-15 18:47 UTC, havi commented on _source/_posts/2021-10-18-security-headers-best-practices.md
> +## Configuring A Security Header
```suggestion
## Configuring a Security Header
```
title case guideline

2021-10-15 18:51 UTC, havi requested changes
Grammar and usage nits, and a typo or two. Great post - glad we got an A!

2021-10-15 20:06 UTC, havi commented on _source/_posts/2021-10-18-security-headers-best-practices.md
> +
```suggestion
### Learn more about Security Headers
```
adding a wrap-up heading

2021-10-15 20:09 UTC, havi requested changes
Adding closing section header, per MRaible suggestion

2021-10-18 15:14 UTC, mraible commented on _source/_posts/2021-10-18-security-headers-best-practices.md
> +There are many different directives of the policy, but the most important one is "script-src", which defines where scripts can be loaded from. Other directives include "default-src", "object-src", "i
Yes, I think so. I'll fix.

2021-10-18 15:16 UTC, mraible commented on _source/_posts/2021-10-18-security-headers-best-practices.md
> +The Referrer-Policy header tells the browser when to send Referrer information. This can help prevent information leakages offsite via Referrer URLs. There are many options for this header, the most
This change alters the meaning of the sentence. The header mentioned here is called "Referrer-Policy" and is spelled correctly. There's also the "Referer" header, which is not spelled correctly.

2021-10-18 16:24 UTC, havi approved these changes
thanks for addressing nits. ready to ship

2021-10-18 16:26 UTC, merged