Intro Alisa
oktadev/okta-blog pull request #924
Opened 2021-10-15 22:07 UTC by alisaduncan

This blog post has the following features:

- [ ] A GitHub Repository with a polished README
- [ ] A GitHub Repository under the github.com/oktadev account
- [x] A title that's approved by Dev Advocacy
- [x] A URL that's approved by Dev Advocacy
- [x] The content has been run through Grammarly (https://www.grammarly.com/)
- [x] Rendered locally and confirmed that no Markdown typos exist

2021-10-18 13:29 UTC, havi commented on _source/_data/authors.yml
> +  twitter: https://twitter.com/alisaduncan
```suggestion
  twitter: https://twitter.com/alisaduncan
  
```
I think this needs a newline, but I'm not 100% certain

2021-10-18 13:30 UTC, havi commented on _source/_posts/2021-10-15-alisaduncan-intro.md
> +title: "Flying into Okta"
```suggestion
title: "Flying Into Okta"
```
per the "Convert to Title Case" tool.

2021-10-18 13:48 UTC, havi commented on _source/_posts/2021-10-15-alisaduncan-intro.md
> +tags: [javascript,typescript,angular,advocacy,okta]
```suggestion
tags: [javascript, typescript, angular, advocacy, okta]
```
adding spaces

2021-10-18 13:48 UTC, havi commented on _source/_posts/2021-10-15-alisaduncan-intro.md
> +communities: [javascript,announcement]
```suggestion
communities: [javascript, announcement]
```
adding spaces

2021-10-18 13:53 UTC, havi requested changes
small editorial nits

2021-10-18 14:17 UTC, alisaduncan commented on _source/_posts/2021-10-15-alisaduncan-intro.md
> +title: "Flying into Okta"
Gotcha. I'll remember title casing for the future. thanks!

2021-10-18 14:33 UTC, alisaduncan commented
@havi I addressed all comments and updated the post date.

2021-10-18 22:48 UTC, mraible approved these changes

2021-10-18 22:48 UTC, mraible commented on _source/_posts/2021-10-20-alisa-duncan-intro.md
> +# Flying into Okta
I'd remove this, otherwise there will be two H1's at the top.

2021-10-18 22:49 UTC, mraible commented on _source/_posts/2021-10-20-alisa-duncan-intro.md
> +I'm looking forward to sharing knowledge, sparking your imagination, and hearing about your aspirations and difficulties using Okta developer tooling. Let's keep in touch so we can do so! You can fin
I would add the final link on your handle rather than dev.to, or surround both.

2021-10-18 22:49 UTC, mraible commented on _source/_posts/2021-10-20-alisa-duncan-intro.md
> +image:
Needs social image here.

2021-10-19 15:02 UTC, alisaduncan commented on _source/_posts/2021-10-20-alisa-duncan-intro.md
> +image:
Oops! thanks for the catch

2021-10-20 14:42 UTC, havi approved these changes

2021-10-20 16:22 UTC, merged