things to keep in mind about auth
oktadev/okta-blog pull request #942
Opened 2021-10-27 22:38 UTC by alisaduncan

This blog post has the following features:

- [ ] A GitHub Repository with a polished README
- [ ] A GitHub Repository under the github.com/oktadev account
- [x] A title that's approved by Dev Advocacy
- [x] A URL that's approved by Dev Advocacy
- [x] The content has been run through Grammarly (https://www.grammarly.com/)
- [x] Rendered locally and confirmed that no Markdown typos exist

2021-10-28 19:34 UTC, havi approved these changes
Ship it!

2021-10-29 16:37 UTC, aaronpk requested changes
I made some edits inline, and there is one graphic to swap out, details in slack.

2021-10-29 16:57 UTC, aaronpk approved these changes

2021-10-29 17:04 UTC, merged

2021-10-29 18:28 UTC, havi approved these changes