Add SAML Assertion Flow Grant blog
oktadev/okta-blog pull request #950
Opened 2021-11-02 00:00 UTC by emanor-okta

This blog post has the following features:

- [x] A GitHub Repository with a polished README
- [ ] A GitHub Repository under the github.com/oktadev account
- [x] A title that's approved by Dev Advocacy
- [ ] A URL that's approved by Dev Advocacy
- [x] The content has been run through Grammarly (https://www.grammarly.com/)
- [x] Rendered locally and confirmed that no Markdown typos exist

2021-11-02 14:46 UTC, havi commented on _source/_posts/2021-11-01-saml-assertion-flow-1.adoc
> +by: advocate|contractor
```suggestion
by: internal-contributor
```
category for Okta staff writers not on dev-advocacy team

2021-11-02 14:48 UTC, havi commented on _source/_posts/2021-11-01-saml-assertion-flow-1.adoc
> +author:
```suggestion
author: erik-manor
```

2021-11-16 16:42 UTC, aaronpk requested changes

2021-11-16 16:42 UTC, aaronpk commented on _source/_posts/2021-11-01-saml-assertion-flow-1.adoc
> +author: erik-manor
Needs an entry for Erik in the [authors.yml](https://github.com/oktadev/okta-blog/blob/main/_source/_data/authors.yml) file

2021-11-16 16:42 UTC, aaronpk commented on _source/_posts/2021-11-01-saml-assertion-flow-1.adoc
> +Security Assertion Markup Language (SAML) is an open standard for exchanging authentication and authorization data between parties, in particular, between an identity provider and a service provider.
Can we avoid using the jargon terms "identity provider" and "service provider" in the opening sentence before we've had a chance to define them?

We also need a definition of "SAML Assertion" before assuming the reader knows what it is or how they would get one.

2021-11-16 16:42 UTC, aaronpk commented on _source/_posts/2021-11-01-saml-assertion-flow-1.adoc
> +The same Okta Org will both generate and consume a SAML Assertion. So the OIDC application will consume a SAML Assertion from the same Org it is defined in. To accomplish this a SAML Service Provider
Add a note that this is not a normal workflow, just for this demonstration.

2021-11-16 16:42 UTC, aaronpk commented on _source/_posts/2021-11-01-saml-assertion-flow-1.adoc
> +== Configure the SAML Service Provider Application
We need some sort of definition of the roles involved before diving in. For example what is a "Service Provider"?

2022-03-04 02:16 UTC, mraible commented
@emanor-okta Is this a post you'd still like to publish?

2023-08-03 23:02 UTC, edunham commented
Checked with emanor via Slack and the desired disposition of this PR is closing it out.

2023-08-03 23:02 UTC, closed without merging